export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
     <section className="w-full h-full">
      {children}
    </section>
  )
}
